config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  get '/register', to: 'customers#new'
  get '/shoppingcart', to: 'carts#show'
  post '/add/:product_id', to: 'carts#add', as: 'add'
  delete '/purchase', to: 'carts#purchase', as: 'purchase'
  delete '/remove/:product_id', to: 'carts#remove', as: 'remove'

  resources :sessions, only: [:new, :create, :destroy]
  resources :customers, only: [:new, :create]
  resources :carts, only: [:show]
  resources :products, only: [:index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :customer
  has_many :line_items
  has_many :products, through: :line_items

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, dependent: :destroy

end

app/models/customer.rb
class Customer < ApplicationRecord

  after_initialize :set_defaults
  has_secure_password
  validates :customer_email, presence: true, uniqueness: true
  has_one :cart
  has_many :products, through: :cart

  def set_defaults
    self.cart = Cart.create({cart_total: 0}) if self.cart.nil?
  end

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :cart
  belongs_to :product

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category
  has_many :line_items
  has_many :carts, through: :line_items

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :get_cats

  def get_cats
    @cats = Category.all
  end

  private
    helper_method :current_customer

    def current_customer
      @current_customer ||= Customer.find_by(id: session[:customer_id]) if session[:customer_id]
    end

    def authorize
      redirect_to login_path, alert: "Please login or register to begin adding items to your cart." if current_customer.nil?
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authorize, only: [:show, :add]

  def show
    @products = Product.all
  end

  def add # adds product to shopping cart
    productid = params[:product_id]
    line_item = current_customer.cart.line_items.find_by(product_id: productid)
    if line_item
      line_item.quantity += 1
      line_item.save
    else
      LineItem.create(cart: current_customer.cart, product_id: productid, quantity: 1)
    end
    redirect_to :back
  end

  def remove # removes products from shopping cart
    @product = Product.find_by(id: params[:product_id])
    current_customer.cart.products.delete(@product)
    redirect_to shoppingcart_path
  end

  def purchase # "purchases" items in shopping cart and clears cart
    current_customer.cart.products.destroy_all
    redirect_to shoppingcart_path
    flash[:notice] = "Thank you for your purchase!"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      session[:customer_id] = @customer.id
      redirect_to root_path
    else
      render :new
    end
  end

private
  def customer_params
    params.require(:customer).permit(:customer_name, :customer_email, :password, :password_confirmation)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:cat] == "all" || !params.has_key?(:cat) #shows all products if params id is "cat" or blank
      @products = Product.all
    else #shows products that only have selected category id
      @products = Product.where(category_id: params[:cat])
    end
  end

  def show
    @product = Product.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    customer = Customer.find_by(customer_email: params[:customer_email])
    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id
      redirect_to root_path
    else
      flash.now.alert = "Invalid login. Try again."
      render :new
    end
  end

  def destroy
    session[:customer_id] = nil
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/carts/index.html.erb
<div class="container-fluid">
    <h4>SHOPPING CART</h4>
        <hr>
        <table class="table">
            <thead>
                <tr class="table-header">
                    <th class="col-md-5">ITEM</th>
                    <th class="col-md-3">EDIT</th>
                    <th class="col-md-1">QUANTITY</th>
                    <th class="col-md-3 text-right">SUBTOTAL</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <% @products.each do |product| %>
                        <td>
                            <div class="d-inline-block col-md-4 table-data">
                                <%= link_to (image_tag product.product_image, {height: 110}), product_path(product) %>
                            </div>
                            <div class="d-inline-block col-md-7 table-data">
                                <%= link_to product.product_name, product_path(product) %><br>
                                $<%= product.product_price %>
                            </div>
                        </td>
                        <td><%= link_to "REMOVE", "#" %></td>
                        <td>1</td>
                        <td class="text-right">$<%= product.product_price %></td>
                </tr>
                    <% end %>
            <thead>
                <tr>
                    <td class="col-md-5"></td>
                    <td class="col-md-3"></td>
                    <td class="col-md-1">SUBTOTAL<br><br>GRANDTOTAL</td>
                    <td class="col-md-3 text-right">PRODUCT PRICES SUM<br><br>CART TOTAL</td>
                </tr>
            </thead>

            </tbody>
        </table>
</div>

app/views/carts/show.html.erb
<div class="container-fluid">
    <div class="text-center"><%= notice %></div>
    <h4>SHOPPING CART</h4>
        <hr>
        <% if @current_customer.cart.products.exists? %> <!-- displays products if they have been added to cart -->
            <table class="table">
                <thead>
                    <tr class="table-header">
                        <th class="col-md-5">ITEM</th>
                        <th class="col-md-3">EDIT</th>
                        <th class="col-md-1">QUANTITY</th>
                        <th class="col-md-3 text-right">SUBTOTAL</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <% @current_customer.cart.line_items.each do |item| %>
                            <td>
                                <div class="d-inline-block col-md-4 table-data">
                                    <%= link_to (image_tag item.product.product_image, {height: 110}), product_path(item.product) %>
                                </div>
                                <div class="d-inline-block col-md-7 table-data">
                                    <%= link_to item.product.product_name, product_path(item.product) %><br>
                                    $<%= item.product.product_price %>
                                </div>
                            </td>
                            <td><%= link_to "REMOVE", remove_path(item.product), method: :delete %></td>
                            <td><%= item.quantity %></td>
                            <td class="text-right">$<%= item.product.product_price * item.quantity %></td>
                    </tr>
                        <% end %>
                <thead>
                    <tr>
                        <td class="col-md-5"></td>
                        <td class="col-md-2"></td>
                        <td class="col-md-2">GRAND TOTAL</td>
                        <% @sum = 0 %>
                        <% @current_customer.cart.line_items.each do |line| %>
                            <% @sum += line.quantity * line.product.product_price %>
                        <% end %>
                        <td class="col-md-3 text-right">$<%= @sum %></td>
                    </tr>
                </thead>
                </tbody>
            </table>
            <div class="text-right"><%= button_to "CHECKOUT", purchase_path, method: :delete, class: "button" %></div>
        <% else %> <!-- displays message and button to root path if no products in cart -->
            <br>
            <%= "You currently have no items in your shopping cart." %><br><br><br>
            <%= link_to "$$$ GIVE US YOUR MONEY $$$", root_path, class: "button" %>
        <% end %>
</div>

app/views/customers/new.html.erb
<div class="container-fluid">
    <h4>CREATE AN ACCOUNT</h4>
    <hr>
    <%= form_for @customer do |f| %>
        <% if @customer.errors.any? %>
            <div>
                <h4>FORM IS INVALID!</h4>
                    <% for message in @customer.errors.full_messages %>
                    <%= message %>
                    <% end %>
            </div>
            <br>
        <% end %>
        <div class="field">
            <%= f.label "Name" %><br>
            <%= f.text_field :customer_name %><br><br>
        </div>
        <div class="field">
            <%= f.label "Email Address" %><br>
            <%= f.text_field :customer_email %><br><br>
        </div>
        <div class="field">
            <%= f.label "Password" %><br>
            <%= f.password_field :password %><br><br>
        </div>
        <div class="field">
            <%= f.label "Confirm Password" %><br>
            <%= f.password_field :password_confirmation %><br><br>
        </div>
        <div class="actions"> <%= f.submit "REGISTER", class: "button" %></div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>The Tofu Shop</title>
        <%= csrf_meta_tags %>

        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/css?family=Heebo:100,300" rel="stylesheet">

        <%= favicon_link_tag 'favicon.ico' %>
    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation"> <!-- top nav bar -->
                <div class="navbar-header navbar-center">
                    <a class="navbar-brand" href="/">THE TOFU SHOP</a>
                </div>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <% if current_customer %>
                           <li>Welcome, <%= current_customer.customer_name %></li>
                           <li><%= link_to "LOGOUT", session_path("dummy"), method: :delete %></li>
                        <% else %>
                           <li><%= link_to "REGISTER", register_path %></li>
                           <li><%= link_to "LOGIN", "/login" %></li>
                        <% end %>
                        <% if current_customer %>
                            <% @quantity = 0 %>
                            <% current_customer.cart.line_items.each do |line| %>
                            <% @quantity += line.quantity %>
                        <% end %>
                            <li><%= link_to "CART (#{@quantity})", shoppingcart_path %></li>
                        <% else %>
                            <li><%= link_to "CART (0)", shoppingcart_path %></li>
                        <% end %>
                    </ul>
                </div>
        </nav>

        <nav class="navbar navbar-default category-nav"> <!--  category nav bar -->
            <div class="container-fluid">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="category-links collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                    <ul class="nav navbar-nav">
                        <li><%= link_to "ALL PRODUCTS", root_path(cat: "all") %></li>
                        <% @cats.each do |cat| %>
                            <li><%= link_to cat.category_name, root_path(cat: cat.id) %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container">
            <div class="row">
                <%= yield %>
            </div>
        </div>

        <footer class="footer">
            <%= link_to image_tag("tofu_background.png"), "http://www.instagram.com/tofu_corgi", target: :_blank %>
        </footer>
    </body>
</html>

app/views/products/index.html.erb
<% @products.each do |product| %>
    <div class="d-inline-block col-md-4 text-center product-all">
        <%= link_to (image_tag product.product_image, {height: 300}), product_path(product) %><br>
        <span class="product-name"><%= link_to product.product_name, product_path(product) %></span><br>
        $<%= product.product_price %><br><br>
    </div>
<% end %>

app/views/products/show.html.erb
<div class="d-inline-block col-md-6 text-center product-page">
    <%= image_tag @product.product_image, {height: 500} %><br>
</div>
<div class="d-inline-block col-md-5">
    <span class="category-name">
        <%= @product.category.category_name %>
    </span><br><br>
    <span class="product-page">
        <%= @product.product_name %><br>
        $<%= @product.product_price %><br><br>
        <%= "Description:" %><br>
    </span>
        <%= @product.product_description %><br><br><br>
        <%= button_to "ADD TO CART", add_path(product_id: @product.id), method: :post, class: "button" %>
</div>